server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Mengarahkan semua request ke index.html (Penting untuk React Router SPA)
        try_files $uri $uri/ /index.html;
    }
}
